### ISSUE TITLE
IPTV openatv autotimer issue

### ISSUE THREAD

**Issue by maionline** [oe-alliance/enigma2-plugins#395]
Using an enigma 2 device I can set an Iptv standard timer but the autotimer doesn’t seem to pick up anything

It was discussed previously here but the fix no longer works
https://github.com/oe-alliance/enigma2-plugins/issues/177

**Comment by AbuBaniaz** [comment]
It was never fixed and needs looking at.

**Comment by viscab** [comment]
Sorry to bump, just wondering if anyone is looking at this issue?

**Comment by oottppxx** [comment]
https://github.com/oottppxx/enigma2/tree/master/mods/autotimer has a crude fix for openatv 6.2 and openatv 6.4 current/latest versions (might work in other systems as well, but haven't tested).

It's a really crude fix, didn't really optimized the code paths and didn't touch the glaring bug for searching across all bouquets as that exhausts box memory (at least on mine, YMMV if you do fix it). Also, I didn't want to make further changes to use the service description instead of some part of the URL, so live with it or change it yourself (other files would need to be touched as well, AFAICT).

**Comment by Huevos** [comment]
Why don't you work on the autotimer files directly?

https://github.com/oe-alliance/enigma2-plugins/tree/master/autotimer

**Comment by oottppxx** [comment]
It was just a quick and dirty fix, as I was asked to look into it (I don't/didn't use auto-timers myself); I didn't want to waddle through the git commits to find the right versions, etc... grabbing the pyo was just easier/faster (my git-fu isn't great, either).

It seems like an interesting issue and I might still take another stab at it, and eventually upstream the changes.

**Comment by oottppxx** [comment]
Updated my mods with the "xxl" version, this supports all bouquets without making the box run out of memory (in my experience, YMMV).
