### ISSUE TITLE
[AutoTimer] zapping should not have a margin by default - openatv Timer margin challenge #3

### ISSUE THREAD

**Issue by GhostofGeeeee** [oe-alliance/enigma2-plugins#622]
Zap Timers created by AutoTimer have a margin?
On openatv a zap timer haven't a margin.

**Comment by TwolDE2** [comment]
This was discussed heavily 3 years ago in the OpenViX forum, including by IanSav (OpenATV) who pushed for the margins to be put back, so maybe you will get them to fix their code? 

IanSav,s comments follow……
The issue is that a previous change to this code removed the duration element of Zap timers. Without the duration as soon as the Zap timer fires it immediately triggers its after event.

Apart from this after event issue removing the duration from Zap timers also creates the following issues:
- As the Zap timer no longer has a duration it is no longer able to be displayed in the EPG.
- As the Zap timer effectively finishes when it starts other timers can then take over the tuner and change the service while the Zap timer should actually be active.

All these hacks to the code should be reversed. Zap timers should be put back the way they were originally designed and implemented.

Regards,
Ian.

**Comment by GhostofGeeeee** [comment]
The request isn't to remove.
On openatv it can be displayed on EPG and other side effects are by design and configurable.
I think openatv don't want a margin, others I don't know, maybe we can implement this for openatv!

Thank you & Greetings back

**Comment by jbleyel** [comment]
Hello @GhostofGeeeee ,
the zap timer in ATV has a margin and there is also a default.

**Comment by jbleyel** [comment]
You can add the zapmargin settings support in autotimer if you like.

**Comment by GhostofGeeeee** [comment]
That will be nice.

**Comment by jbleyel** [comment]
> That would be nice.

**You** can add ... if you like.
I have no time for this.

**Comment by GhostofGeeeee** [comment]
Sometimes **I** like to do so but not this, maybe next time.
Please!? I hope this is the last _"Timer margin challenge"_ which I all reported like you(@jbleyel) want, without posting code and tries to fix...
PS: I know you prefer to write new features etc. but we report few bugs, because you don't write a lot of them but please let them unfixed.

**Comment by GhostofGeeeee** [comment]
**Thank you**, yesterday I start working on it...
This will fix the Issue but i found more to improve on this scenario!("Change default recording offset"->"On" starts with 5+5 and ignore defaults of openatv for zap and normal)
You? or do you later want to see my try?
Can AutoTimer create a Timer(Zap)with disabled setEndTime? <- I got stuck on it.
On normal TimerEdit setEndTime is always On and endTime is start or end time but possible to disable it?
